### ISSUE TITLE
Error while executing run_taxocom.sh

### ISSUE THREAD

**Issue by ieea** [donalee/taxocom#2]
Please help !! At first I thought it's the issue of mismatch of terms in terms.txt & seed_taxo. So I manually corrected all and system is able to read but again I got the issue.
####################
Starting cell * with 323 docs.
Starting training using file ../data/auto/root_seed_taxo/docs.txt
Loading embedding from file ../data/auto/root_seed_taxo/embeddings.txt
Category name file: ../data/auto/root_seed_taxo/child_names.txt
Target category charging : charging Smart products EV plugs cables connectors stations Charger 
Target category Battery : Battery sustainable swapping models service interoperability 
Target category bidirectional : bidirectional charging home charger CCS Smart products EV plugs cables connectors stations Charger 
Target category wireless : wireless parking electrified roadways network inductive 

[Main] Finish locally discriminative embedding - 3.5880656242370605 seconds
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    main(args)
  File "main.py", line 58, in main
    recur(input_corpus, root_dir, '*', args.filter_tau, args.n_locterms, args.betas, 0)
  File "main.py", line 23, in recur
    child_names = run_clustering(input_corpus, filter_tau, betas, node_name, node_dir, level)
  File "/home/fidev/taxocom/code/clustering.py", line 101, in run_clustering
    doc_clusters = dataset.get_doc_clusters(term_clusters, term_rel_scores)
  File "/home/fidev/taxocom/code/dataset.py", line 185, in get_doc_clusters
    term_assignment[term_id] = clus_id
IndexError: list assignment index out of range
Compress the output taxonomy
#################

**Comment by donalee** [comment]
Hi, Did you solve the issue? That part hardly raises errors, so it seems weird. I recommend you to debug it using python debugger (pdb) to figure out which part does not work correctly.
